// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.velotrack.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object VelotrackApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class TrackingState(val raw: Int) {
  IDLE(0),
  TRACKING(1),
  PAUSED(2);

  companion object {
    fun ofRaw(raw: Int): TrackingState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GpsPointDto (
  val lat: Double,
  val lng: Double,
  val timestamp: Long,
  val speed: Double? = null,
  val altitude: Double? = null,
  val accuracy: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GpsPointDto {
      val lat = pigeonVar_list[0] as Double
      val lng = pigeonVar_list[1] as Double
      val timestamp = pigeonVar_list[2] as Long
      val speed = pigeonVar_list[3] as Double?
      val altitude = pigeonVar_list[4] as Double?
      val accuracy = pigeonVar_list[5] as Double?
      return GpsPointDto(lat, lng, timestamp, speed, altitude, accuracy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lat,
      lng,
      timestamp,
      speed,
      altitude,
      accuracy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GpsPointDto
    return VelotrackApiPigeonUtils.deepEquals(this.lat, other.lat) && VelotrackApiPigeonUtils.deepEquals(this.lng, other.lng) && VelotrackApiPigeonUtils.deepEquals(this.timestamp, other.timestamp) && VelotrackApiPigeonUtils.deepEquals(this.speed, other.speed) && VelotrackApiPigeonUtils.deepEquals(this.altitude, other.altitude) && VelotrackApiPigeonUtils.deepEquals(this.accuracy, other.accuracy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.lat)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.lng)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.timestamp)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.speed)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.altitude)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.accuracy)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RideDto (
  val id: String,
  val title: String,
  val startTime: Long,
  val endTime: Long? = null,
  val points: List<GpsPointDto?>,
  val totalDistance: Double,
  val avgSpeed: Double,
  val maxSpeed: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RideDto {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val startTime = pigeonVar_list[2] as Long
      val endTime = pigeonVar_list[3] as Long?
      val points = pigeonVar_list[4] as List<GpsPointDto?>
      val totalDistance = pigeonVar_list[5] as Double
      val avgSpeed = pigeonVar_list[6] as Double
      val maxSpeed = pigeonVar_list[7] as Double
      return RideDto(id, title, startTime, endTime, points, totalDistance, avgSpeed, maxSpeed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      startTime,
      endTime,
      points,
      totalDistance,
      avgSpeed,
      maxSpeed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RideDto
    return VelotrackApiPigeonUtils.deepEquals(this.id, other.id) && VelotrackApiPigeonUtils.deepEquals(this.title, other.title) && VelotrackApiPigeonUtils.deepEquals(this.startTime, other.startTime) && VelotrackApiPigeonUtils.deepEquals(this.endTime, other.endTime) && VelotrackApiPigeonUtils.deepEquals(this.points, other.points) && VelotrackApiPigeonUtils.deepEquals(this.totalDistance, other.totalDistance) && VelotrackApiPigeonUtils.deepEquals(this.avgSpeed, other.avgSpeed) && VelotrackApiPigeonUtils.deepEquals(this.maxSpeed, other.maxSpeed)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.id)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.title)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.startTime)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.endTime)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.points)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.totalDistance)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.avgSpeed)
    result = 31 * result + VelotrackApiPigeonUtils.deepHash(this.maxSpeed)
    return result
  }
}
private open class VelotrackApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TrackingState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GpsPointDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RideDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TrackingState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is GpsPointDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is RideDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VeloNativeApi {
  fun startTracking(rideId: String, title: String, callback: (Result<Unit>) -> Unit)
  fun pauseTracking(callback: (Result<Unit>) -> Unit)
  fun resumeTracking(callback: (Result<Unit>) -> Unit)
  fun stopTracking(callback: (Result<RideDto>) -> Unit)
  fun getState(callback: (Result<TrackingState>) -> Unit)
  fun listRides(callback: (Result<List<RideDto>>) -> Unit)
  fun getRide(id: String, callback: (Result<RideDto?>) -> Unit)
  fun deleteRide(id: String, callback: (Result<Unit>) -> Unit)
  fun analyzeRide(id: String, callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by VeloNativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      VelotrackApiPigeonCodec()
    }
    /** Sets up an instance of `VeloNativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VeloNativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.startTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val rideIdArg = args[0] as String
            val titleArg = args[1] as String
            api.startTracking(rideIdArg, titleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(VelotrackApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.pauseTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.pauseTracking{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(VelotrackApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.resumeTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.resumeTracking{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(VelotrackApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.stopTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopTracking{ result: Result<RideDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VelotrackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.getState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getState{ result: Result<TrackingState> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VelotrackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.listRides$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listRides{ result: Result<List<RideDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VelotrackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.getRide$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.getRide(idArg) { result: Result<RideDto?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VelotrackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.deleteRide$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.deleteRide(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(VelotrackApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.velotrack.VeloNativeApi.analyzeRide$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.analyzeRide(idArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VelotrackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VelotrackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VeloFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VeloFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      VelotrackApiPigeonCodec()
    }
  }
  fun onLocation(pointArg: GpsPointDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.velotrack.VeloFlutterApi.onLocation$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pointArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VelotrackApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onElapsed(elapsedMsArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.velotrack.VeloFlutterApi.onElapsed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(elapsedMsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VelotrackApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onError(codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.velotrack.VeloFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VelotrackApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
